import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Navigation from './(components)/Navigation';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Christmas Lottery',
  description: 'Generated by Piotrek',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pl" suppressHydrationWarning={true}>
      <body className={inter.className} suppressHydrationWarning={true}>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
